redis:
  ## Redis docker image
  image:
    tag: ""

  ## Prometheus metrics and service monitor configuration
  metrics:
    ## Enable metrics export
    enabled: false

  ## Resource limits and requests (for Redis)
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  ## Use Kubernetes Deployment instead of StatefulSet when in Non-HA mode
  useDeploymentWhenNonHA: true

  ## High availability mode (with master-slave replication and sentinel)
  haMode:
    ## Enable high availibility deployment mode
    enabled: false
    ## Use DNS names instead of Pod IPs to build the cluster
    useDnsNames: false
    ## Mandatory redis HA-master group name (default "redisha")
    masterGroupName: "redisha"
    ## Number of replicas (minimum should be 3)
    replicas: 3
    ## Quorum of sentinels that need to agree that a master node is not available
    quorum: 2


  ## Storage parameters
  storage:

    ## Internal volume name and prefix of a created PVC
    volumeName: "redis-data"

    ## Alternative set requestedSize to define a size for a dynmaically created PVC
    requestedSize:

    ## the storage class name
    className:

    ## Default access mode (ReadWriteOnce)
    accessModes:
      - ReadWriteOnce

    ## Keep a created Persistent volume claim when uninstalling the helm chart (only for non-HA mode with option useDeploymentWhenNonHA: true)
    keepPvc: false
