apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kubero-operator
  name: kubero-operator-kuberoaddonmongodb-admin-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoaddonmongodbs
  verbs:
  - '*'
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoaddonmongodbs/status
  verbs:
  - get
