apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kubero-operator
  name: kubero-operator-kuberoaddonredis-viewer-role
rules:
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoaddonredis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kubero.dev
  resources:
  - kuberoaddonredis/status
  verbs:
  - get
