apiVersion: v2
appVersion: 3.1.0
description: A Helm chart for Kuberos RabbitMQ addon
name: kuberoaddonrabbitmq
type: application
version: 0.1.0
dependencies:
  - name: rabbitmq
    repository: https://groundhog2k.github.io/helm-charts/
    version: 2.x.x
