rabbitmq:

  ## RabbitMQ docker image
  image:
    tag: ""

  ## Number of replicas
  replicaCount: 1

  ## Service monitor configuration for Prometheus metrics
  ## Prometheus plugin must be enabled to use this
  serviceMonitor:
    ## Enable service monitor
    enabled: false

  ## Maximum number of revisions maintained in revision history
  revisionHistoryLimit:

  ## Default Kubernetes cluster domain
  clusterDomain: cluster.local

  # A list of plugins (without whitespace!) - f.e.: rabbitmq_federation_management,rabbitmq_mqtt,rabbitmq_stomp
  plugins: []

  # Default user and erlang cookie
  # The erlang cookie is important for clustered or container based usage
  # Find more information about it at https://hub.docker.com/_/rabbitmq and https://www.rabbitmq.com/clustering.html#erlang-cookie
  # The erlang cookie is a MANDATORY value
  authentication:
    user:
      value: "kubero_user"

    ## Initial password (alternative: set environment variable RABBITMQ_DEFAULT_PASS)
    password:
      value: "kubero_password"

    ## Erlang cookie (MANDATORY) (alternative: set environment variable ERLANG_COOKIE)
    erlangCookie:
      value: "kubero_erlang_cookie"

  # RabbitMQ specific configuration options described at https://www.rabbitmq.com/configure.html#config-items
  options:
    ## High memory watermark option is described at https://www.rabbitmq.com/memory.html
    memoryHighWatermark:
      ## Enables high memory watermark configuration (default: false)
      enabled: false
      ## Type of watermark value (relative or absoulte - default: relative)
      type: "relative"
      ## High memory watermark value (default: 0.4 - 40%)
      value: 0.4
      ## Paging threshold when RabbitMQ starts paging queue content before high memory watermark is reached
      pagingRatio:
    ## Memory options are described at https://www.rabbitmq.com/configure.html
    memory:
      ## Overwrites the value that is automatically calculated from resource.limits.memory
      totalAvailableOverrideValue:
      ## Strategy for memory usage report (rss or allocated)
      calculationStrategy:

  managementPlugin:
    enabled: false

  ## Prometheus plugin options
  prometheusPlugin:
    enabled: true


  ## Storage parameters
  storage:

    ## Internal volume name
    volumeName: "rabbitmq-volume"

    ## Alternative set requestedSize to define a size for a dynamically created PVC
    requestedSize:

    ## the storage class name
    className:

    ## Default access mode (ReadWriteOnce)
    accessModes:
      - ReadWriteOnce
