elasticsearch:
  global:
    imageRegistry: "bitnamilegacy"
    storageClass: ""
  security:
    ## @param security.elasticPassword Password for 'elastic' user
    ## Ref: https://github.com/bitnami/containers/tree/main/bitnami/elasticsearch#security
    ##
    elasticPassword: ""
    tls:
      verificationMode: "none"

  ## @section Master-elegible nodes parameters
  master:
    ## @param master.replicaCount Number of master-elegible replicas to deploy
    ##
    replicaCount: 2
    ## @param master.persistence.size PVC Storage Request for master data volume
    ##
    persistence:
      size: 8Gi

  ## @section Data-only nodes parameters
  data:
    ## @param data.replicaCount Number of data-only replicas to deploy
    ##
    replicaCount: 2
    ## Enable persistence using Persistent Volume Claims
    ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      ## @param data.persistence.size Persistent Volume Size
      ##
      size: 8Gi

  ## @section Ingest-only nodes parameters
  ingest:
    ## @param ingest.enabled Enable ingest nodes
    ##
    enabled: true
    ## @param ingest.replicaCount Number of ingest-only replicas to deploy
    ##
    replicaCount: 2